### ISSUE TITLE
Treating "0" outputs

### ISSUE THREAD

**Issue by pedrocleis** [altre/alfred_python_interpreter#1]
Hi,
I've being using it and sometimes it bothers me that when the output is 0 or 0.0 it just shows nothing instead of showing the result as being 0 or 0.0.

Best Regards,
Pedro

**Comment by altre** [comment]
Ok, thanks for the remark. Should be fixed. Go ahead and try it!

**Comment by pedrocleis** [comment]
It's working now, thank you!
